# platform :ios, '9.0'

target 'UXSDKSwiftSample' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '4.11'
  pod 'DJI-UXSDK-iOS', '4.11'
  pod 'DJIWidget', '1.6.1'
  pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
  pod 'iOS-Color-Picker'
end
