# platform :ios, '10.0'

target 'UXSDKOCSample' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '~> 4.11.1'
  pod 'DJI-UXSDK-iOS', '~> 4.11'
  pod 'DJIWidget', '~> 1.6.2'
  pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
end
