platform :ios, '10.0'

target 'UXSDKOCSample' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '~> 4.14-trial1'
  pod 'DJI-UXSDK-iOS', '~> 4.14-trial1'
  pod 'DJIWidget', '~> 1.6.3'
  pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'

end
