platform :ios, '10.0'

target 'UXSDKOCSample' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '~> 4.16.2'
  pod 'DJI-UXSDK-iOS', '~> 4.16.2'
  pod 'DJIWidget', '~> 1.6.8'
  pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.18'

end
